FROM python:3.8

RUN apt-get update
